### ISSUE TITLE
Authorization Issues

### ISSUE THREAD

**Issue by wboykinm** [mapbox/github-file-browser#1]
A visit to the demo registers:

`Failed to load resource: the server responded with a status of 401 (Unauthorized) https://api.github.com/user/repos`

Not sure what up there.

**Comment by tmcw** [comment]
Yeah, for now the demo expects a github_token but doesn't have one. Not sure if I'm going to write the full auth loop just for the standalone demo.

**Comment by wboykinm** [comment]
Fair. I'll fork.
